### ISSUE TITLE
Android Asset Importer threw an uncaught PluginException

### ISSUE THREAD

**Issue by zdl411437734** [david-serrano/AndroidAssetImporter#1]
上午10:03:38 Plugin Error: Android Asset Importer threw an uncaught PluginException. Disable Plugin
上午10:03:38 PluginException: cannot create class "InfoDialog" [Plugin: com.davy307.androidassetimporter]

Android studio 1.5.1

**Comment by david-serrano** [comment]
cool thanks! will look into this

**Comment by david-serrano** [comment]
hi zdl411437734  sorry this is a bit late, but after some investigation, the conclusion i have reached is that your android stuido must run off of some version of jdk 1.8 (point your JAVA_HOME environment variable to the top level folder and restart android studio) - http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by asgarddesigns** [comment]
I am getting this error with Android Studio 2.1.2. 

when running AS with JDK 1.8 there is no error thrown but the option still does not show in the new> menu.

On mac > JDK 1.6 has font issues so is generally not recommended for now:

http://tools.android.com/tech-docs/configuration/osx-jdk
